import {useCallback,useEffect,useRef,useState} from 'react';
import {supabase} from '@/lib/supabase';
import {useAuth} from '@/context/AuthContext';
type Quote={id:string;quote_number:string;title:string;subtotal:number;discount:number;tax:number;delivery_fee:number;total:number;status:string;valid_until:string|null};
export function PrintQuotes(){
 const {user}=useAuth();const [rows,setRows]=useState<Quote[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[q,setQ]=useState('');
 const scope=useRef(user?.id);scope.current=user?.id;
 const load=useCallback(async()=>{if(!user)return;const r=await supabase.from('print_quotes').select('id,quote_number,title,subtotal,discount,tax,delivery_fee,total,status,valid_until').eq('user_id',user.id).order('created_at',{ascending:false});if(r.error)throw r.error;return r.data as Quote[];},[user?.id]);
 useEffect(()=>{let active=true;setRows([]);setError('');setBusy(false);void load().then(r=>{if(active)setRows(r||[]);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false};},[load]);
 async function respond(id:string,status:'accepted'|'rejected'){if(busy||!user)return;const actor=user.id;setBusy(true);setError('');try{const r=await supabase.from('print_quotes').update({status}).eq('id',id).eq('user_id',user.id).eq('status','issued').select('id');if(r.error)throw r.error;if(!r.data?.length)throw new Error('Quote was not changed. Refresh and check access or expiry.');const fresh=await load();if(scope.current===actor)setRows(fresh||[]);}catch(e){if(scope.current===actor)setError(e instanceof Error?e.message:'Could not save quote response.');}finally{if(scope.current===actor)setBusy(false);}}
 return <main className="mx-auto max-w-6xl p-6"><div className="flex justify-between gap-4"><div><h1 className="text-3xl font-black">My quotations</h1><p className="mt-2 text-sm">Review the approved costs before accepting. Acceptance allows IHLink to issue an invoice.</p></div><button className="h-fit rounded-xl border p-3" onClick={()=>window.print()}>Print / save PDF</button></div>{error&&<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}<label className="mt-5 block">Search quotations<input type="search" className="mt-1 w-full rounded-xl border p-3" value={q} onChange={e=>setQ(e.target.value)}/></label><div className="mt-5 space-y-4">{rows.filter(r=>(r.quote_number+' '+r.title+' '+r.status).toLowerCase().includes(q.toLowerCase())).map(r=><article className="rounded-2xl border bg-white p-5" key={r.id}><h2 className="font-bold">{r.quote_number} — {r.title}</h2><p className="mt-2">Subtotal ₦{Number(r.subtotal).toLocaleString()} · Discount ₦{Number(r.discount).toLocaleString()} · Tax ₦{Number(r.tax).toLocaleString()} · Delivery ₦{Number(r.delivery_fee).toLocaleString()}</p><p className="mt-2 font-bold">Total ₦{Number(r.total).toLocaleString()} · {r.status} · Valid until {r.valid_until||'Not specified'}</p>{r.status==='issued'&&r.valid_until&&r.valid_until>=new Date().toISOString().slice(0,10)&&<div className="mt-4 flex gap-3 print:hidden"><button disabled={busy} className="rounded-xl bg-pink-700 p-3 text-white" onClick={()=>void respond(r.id,'accepted')}>Accept quotation</button><button disabled={busy} className="rounded-xl border p-3" onClick={()=>void respond(r.id,'rejected')}>Reject quotation</button></div>}</article>)}{!rows.length&&<p>No quotation has been issued for your account.</p>}</div></main>;
}
