import { useEffect,useState } from 'react';
import { Link } from 'react-router-dom';
import { PrintHeader,PrintFooter } from '@/components/PrintShell';
import { ManagedContentSections } from '@/components/ManagedContentSections';
import { supabase } from '@/lib/supabase'; import { ArrowRight,Upload,Truck,Palette,Printer,BookOpen,Shirt,ScanLine,Image as ImageIcon,Badge,Layers,PenTool } from 'lucide-react';
type Product={id:string;name:string;description:string|null;category:string;base_price:number|null;};
const servicePhotos=['Flyers & brochures','Business cards','Banners & roll-ups','Apparel branding','Gifts & souvenirs','Stamps & ID cards','Binding & documents','Signage & stickers','Awards, trophies & plaques'];
function ServiceVisual({name}:{name:string}){const n=name.toLowerCase();if(/award|troph|plaque/.test(n))return <img src="/images/ihlink-awards.webp" alt="IHLink awards, trophies and plaques product illustration" width="1672" height="941" className="aspect-[4/3] w-full object-cover"/>;const tile=n.includes('card')&&!n.includes('id')?1:n.includes('banner')||n.includes('roll')?2:n.includes('apparel')||n.includes('shirt')||n.includes('wear')?3:n.includes('gift')||n.includes('mug')||n.includes('souvenir')?4:n.includes('stamp')||n.includes('id')?5:n.includes('bind')||n.includes('book')||n.includes('document')?6:n.includes('sign')||n.includes('sticker')?7:0;return <div role="img" aria-label={name+' — IHLink branded service illustration'} className="aspect-[4/3] bg-no-repeat" style={{backgroundImage:'url(/images/print-services.webp)',backgroundSize:'800% auto',backgroundPosition:`${tile/7*100}% 89%`}}/>}
export function PrintBrandingHome(){const [products,setProducts]=useState<Product[]>([]);useEffect(()=>{if(!supabase)return;void supabase.from('print_products').select('id,name,description,category,base_price').eq('active',true).order('name').then(({data})=>setProducts((data||[]) as Product[]));},[]);
return <div className="min-h-screen bg-white"><PrintHeader/><main>
<section className="bg-gradient-to-br from-pink-50 via-white to-sky-50"><div className="max-w-[1440px] mx-auto px-6 lg:px-10 py-16 lg:py-24 grid lg:grid-cols-2 gap-12 items-center"><div><p className="font-bold text-pink-600 uppercase tracking-wider">IHLink Print & Branding</p><h1 className="mt-3 text-4xl lg:text-6xl font-extrabold">Your vision. Our print.</h1><p className="mt-5 text-lg text-muted">Professional print, branding, signage, apparel, souvenirs, awards, trophies and custom production—from quotation to tracked completion.</p><div className="mt-8 flex gap-3 flex-wrap"><Link to="/print/order" className="px-6 py-3 rounded-xl bg-royal-600 text-white font-bold">Start an Order</Link><Link to="/print/order" className="px-6 py-3 rounded-xl border font-bold">Request a Quote</Link><Link to="/print/dashboard" className="px-6 py-3 rounded-xl border font-bold">Track Orders</Link></div></div><figure><img src="/images/print-services.webp" alt="IHLink branded printing studio, apparel, gifts, stationery, signage and binding service concepts" width="1672" height="941" className="w-full rounded-3xl shadow-xl"/><figcaption className="mt-3 text-xs text-muted">IHLink branded service illustrations.</figcaption></figure></div></section>
<section className="max-w-[1440px] mx-auto px-6 lg:px-10 py-16"><h2 className="text-3xl font-extrabold">Products & services</h2><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{servicePhotos.map(name=><figure key={name} className="overflow-hidden rounded-2xl border"><ServiceVisual name={name}/><figcaption className="p-3 font-bold">{name}</figcaption></figure>)}</div><p className="mt-2 text-muted">Only activated catalogue items are displayed. Pricing is shown only when configured.</p>{products.length?<div className="mt-8 grid sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-5">{products.map(p=><div key={p.id} className="rounded-2xl border overflow-hidden"><ServiceVisual name={p.name}/><div className="p-5"><p className="text-xs uppercase font-bold text-muted">{p.category}</p><h3 className="mt-1 font-extrabold text-lg">{p.name}</h3><p className="mt-2 text-sm text-muted">{p.description}</p><div className="mt-4 flex justify-between items-center">{p.base_price!=null&&Number(p.base_price)>0?<span className="font-bold">From ₦{Number(p.base_price).toLocaleString()}</span>:<span className="text-sm text-muted">Quote based</span>}<Link to="/print/order" className="text-royal-600"><ArrowRight/></Link></div></div></div>)}</div>:<div className="mt-8 rounded-2xl border bg-slate-50 p-8"><h3 className="font-extrabold">Catalogue activation in progress</h3><p className="mt-2 text-sm text-muted">Products will appear here after approved specifications and prices are activated. No placeholder prices are being published.</p></div>}</section>
<section className="bg-slate-50 border-y"><div className="max-w-[1440px] mx-auto px-6 lg:px-10 py-14 grid md:grid-cols-3 gap-6">{[[Palette,'Configure','Choose dimensions, material, quantity and finishing.'],[Upload,'Artwork','Upload your artwork or request design support.'],[Truck,'Track','Follow quotation, payment, production, quality control and delivery.']].map(([I,t,d])=>{const Icon=I as typeof Palette;return <div key={t as string} className="bg-white border rounded-2xl p-6"><Icon className="w-8 h-8 text-royal-600"/><h3 className="mt-4 font-extrabold">{t as string}</h3><p className="mt-2 text-sm text-muted">{d as string}</p></div>})}</div></section>
<ManagedContentSections pageKey="print"/></main><PrintFooter/></div>}