import { useEffect,useState } from "react";
import { Link } from "react-router-dom";
import { supabase } from "@/lib/supabase";
import { useAuth } from "@/context/AuthContext";
type Order={id:string;order_number:string;title:string;status:string;priority:string;due_at:string|null;fulfillment:string};
type Proof={id:string;order_id:string;version:number;status:string;customer_notes:string|null};
type Invoice={id:string;invoice_number:string;amount:number;amount_paid:number;status:string;due_at:string|null};
export function PrintWorkspace(){const{user,loading,signOut}=useAuth();const[orders,setOrders]=useState<Order[]>([]),[proofs,setProofs]=useState<Proof[]>([]),[invoices,setInvoices]=useState<Invoice[]>([]),[search,setSearch]=useState(""),[title,setTitle]=useState(""),[fulfillment,setFulfillment]=useState("pickup"),[notice,setNotice]=useState("");
useEffect(()=>{if(!user)return;void Promise.all([supabase.from("print_orders").select("id,order_number,title,status,priority,due_at,fulfillment").order("created_at",{ascending:false}),supabase.from("print_proofs").select("id,order_id,version,status,customer_notes").order("created_at",{ascending:false}),supabase.from("print_invoices").select("id,invoice_number,amount,amount_paid,status,due_at").order("created_at",{ascending:false})]).then(([o,p,i])=>{setOrders((o.data||[])as Order[]);setProofs((p.data||[])as Proof[]);setInvoices((i.data||[])as Invoice[])})},[user]);
if(loading)return <div className="p-8">Loading…</div>;if(!user)return <div className="max-w-xl mx-auto p-8"><h1 className="text-3xl font-extrabold">Print & Branding workspace</h1><p className="mt-3 text-muted">Sign in to request quotes, upload artwork, approve proofs and track production.</p><Link className="inline-block mt-5 px-5 py-3 rounded-xl bg-blue-700 text-white font-bold" to="/signin?next=/print/dashboard">Sign in</Link></div>;
const visible=orders.filter(o=>!search||(o.order_number+" "+o.title+" "+o.status).toLowerCase().includes(search.toLowerCase()));
async function request(){if(!title.trim())return;const{error}=await supabase.from("print_orders").insert({user_id:user.id,title:title.trim(),fulfillment,status:"request"});if(error)setNotice(error.message);else{setNotice("Print request submitted.");setTitle("");location.reload()}}
async function proof(id:string,status:string){const{error}=await supabase.from("print_proofs").update({status,approved_at:status==="approved"?new Date().toISOString():null}).eq("id",id);setNotice(error?.message||("Proof "+status));if(!error)location.reload()}
return <main className="min-h-screen bg-slate-50 p-5 lg:p-8"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-bold text-pink-600">IHLink Print & Branding</p><h1 className="text-3xl font-extrabold">Customer workspace</h1></div><div className="flex gap-2"><Link to="/print" className="rounded-xl border bg-white px-4 py-2">Storefront</Link><button className="rounded-xl border bg-white px-4 py-2" onClick={()=>window.print()}>Print / Save PDF</button><button className="rounded-xl border bg-white px-4 py-2" onClick={()=>void signOut()}>Sign out</button></div></div>{notice&&<div className="mt-4 rounded-xl border bg-white p-3">{notice}</div>}
<div className="mt-6 grid gap-5 lg:grid-cols-3"><section className="rounded-2xl border bg-white p-5 lg:col-span-2"><div className="flex flex-wrap justify-between gap-3"><h2 className="font-extrabold">Orders & production</h2><input className="rounded-xl border px-3 py-2" placeholder="Search orders..." value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="mt-4 max-h-[420px] overflow-auto"><table className="w-full min-w-[700px] text-sm"><thead className="sticky top-0 bg-slate-100"><tr><th className="p-3 text-left">Order</th><th>Project</th><th>Status</th><th>Priority</th><th>Fulfillment</th></tr></thead><tbody>{visible.map(o=><tr className="border-t" key={o.id}><td className="p-3 font-bold">{o.order_number}</td><td>{o.title}</td><td className="capitalize">{o.status.replaceAll("_"," ")}</td><td>{o.priority}</td><td>{o.fulfillment}</td></tr>)}</tbody></table></div></section>
<section className="rounded-2xl border bg-white p-5"><h2 className="font-extrabold">New print request</h2><input className="mt-4 w-full rounded-xl border p-3" placeholder="e.g. 500 business cards" value={title} onChange={e=>setTitle(e.target.value)}/><select className="mt-3 w-full rounded-xl border p-3" value={fulfillment} onChange={e=>setFulfillment(e.target.value)}><option value="pickup">Pickup</option><option value="delivery">Delivery</option></select><button className="mt-3 w-full rounded-xl bg-blue-700 p-3 font-bold text-white" onClick={()=>void request()}>Request quote / job</button></section></div>
<div className="mt-5 grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border bg-white p-5"><h2 className="font-extrabold">Artwork proofs</h2><div className="mt-3 divide-y">{proofs.map(p=><div className="py-3" key={p.id}><div className="flex justify-between"><b>Proof v{p.version}</b><span className="capitalize">{p.status}</span></div>{p.status==="pending"&&<div className="mt-2 flex gap-2"><button className="rounded-lg border px-3 py-1" onClick={()=>void proof(p.id,"approved")}>Approve</button><button className="rounded-lg border px-3 py-1" onClick={()=>void proof(p.id,"revision_requested")}>Request revision</button></div>}</div>)}{!proofs.length&&<p className="py-4 text-sm text-muted">No proofs awaiting review.</p>}</div></section>
<section className="rounded-2xl border bg-white p-5"><h2 className="font-extrabold">Invoices & balances</h2><div className="mt-3 divide-y">{invoices.map(i=><div className="flex justify-between py-3" key={i.id}><div><b>{i.invoice_number}</b><p className="text-xs capitalize text-muted">{i.status}</p></div><div className="text-right"><b>₦{i.amount.toLocaleString()}</b><p className="text-xs text-muted">Due ₦{Math.max(0,i.amount-i.amount_paid).toLocaleString()}</p></div></div>)}{!invoices.length&&<p className="py-4 text-sm text-muted">No invoices yet.</p>}</div></section></div></div></main>}
