import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import {supabase} from '@/lib/supabase';
type Row=Record<string,unknown>;
type Mode='operations'|'artwork'|'inventory'|'qc'|'delivery';
const input='mt-1 block w-full rounded-xl border bg-white p-2.5';
export function PrintStaffActions({canEdit,userId,onSaved,mode='operations'}:{canEdit:boolean;userId:string;mode?:Mode;onSaved?:()=>void}){
 const [data,setData]=useState<Record<string,Row[]>>({}),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[form,setForm]=useState<Record<string,string>>({});
 const scope=useRef(userId);scope.current=userId;
 const load=useCallback(async()=>{if(!supabase)throw new Error('Database unavailable.');const pairs=await Promise.all(['print_orders','print_quotes','print_jobs','print_inventory','print_artworks'].map(async table=>{const r=await supabase!.from(table).select('*').limit(300);if(r.error)throw r.error;return [table,r.data||[]] as const;}));return Object.fromEntries(pairs);},[userId]);
 useEffect(()=>{let active=true;setData({});setForm({});setError('');setNotice('');setBusy(false);setLoading(true);void load().then(d=>{if(active)setData(d);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false};},[load]);
 async function submit(e:FormEvent,rpc:string,args:Record<string,unknown>){e.preventDefault();if(!canEdit||busy||!supabase)return;const identity=scope.current;setBusy(true);setError('');setNotice('');try{const r=await supabase.rpc(rpc,args);if(r.error)throw r.error;const d=await load();if(identity===scope.current){setData(d);setForm({});setNotice('Saved successfully.');onSaved?.();}}catch(e){if(identity===scope.current)setError(e instanceof Error?e.message:'Save failed.');}finally{if(identity===scope.current)setBusy(false);}}
 const field=(key:string,title:string,type='text',required=true)=><label>{title}<input className={input} type={type} required={required} step={type==='number'?'0.01':undefined} value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>;
 const select=(key:string,title:string,rows:Row[],display:(r:Row)=>string)=><label>{title}<select required className={input} value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}><option value="">Choose {title.toLowerCase()}</option>{rows.map(r=><option key={String(r.id)} value={String(r.id)}>{display(r)}</option>)}</select></label>;
 const orderSelect=select('order','Order',data.print_orders||[],r=>String(r.order_number)+' — '+String(r.title)+' ('+String(r.status)+')');
 const button=<button disabled={busy||loading} className="rounded-xl bg-pink-700 px-4 py-2 font-bold text-white disabled:opacity-50">{busy?'Saving…':'Save'}</button>;
 const card='rounded-2xl border bg-white p-5';const grid='mt-4 grid gap-3 md:grid-cols-2';
 if(!canEdit)return <p className="mt-5 rounded-xl border p-4 text-sm">You have read-only Print access. Staff actions require edit permission.</p>;
 return <section className="my-6 space-y-4 print:hidden" aria-label="Print staff actions">{error&&<p role="alert" className="rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}{notice&&<p role="status" className="rounded-xl bg-green-50 p-4">{notice}</p>}{loading&&<p role="status">Loading authorized workflow records…</p>}
 {mode==='operations'&&<><article className={card}><h2 className="font-bold">Issue a priced quotation</h2><form className={grid} onSubmit={e=>void submit(e,'print_issue_quote',{p_order:form.order,p_subtotal:Number(form.subtotal),p_discount:Number(form.discount||0),p_tax:Number(form.tax||0),p_delivery:Number(form.delivery||0),p_valid_until:form.valid_until})}>{orderSelect}{field('subtotal','Approved subtotal (NGN)','number')}{field('discount','Discount (NGN)','number',false)}{field('tax','Tax (NGN)','number',false)}{field('delivery','Delivery charge (NGN)','number',false)}{field('valid_until','Quote expiry','date')}{button}</form></article>
 <article className={card}><h2 className="font-bold">Invoice a customer-accepted quotation</h2><p className="mt-2 text-sm">The server copies the accepted quote total. An invoice cannot be issued twice.</p><form className={grid} onSubmit={e=>void submit(e,'print_invoice_accepted_quote',{p_order:form.order,p_due_at:form.due_at?new Date(form.due_at).toISOString():null})}>{orderSelect}{field('due_at','Due date','date',false)}{button}</form></article>
 <article className={card}><h2 className="font-bold">Advance paid production</h2><p className="mt-2 text-sm">Verified full payment and customer-approved artwork are required.</p><form className={grid} onSubmit={e=>void submit(e,'print_advance_job',{p_order:form.order,p_stage:form.stage,p_notes:form.notes||null})}>{orderSelect}<label>Next stage<select required className={input} value={form.stage||''} onChange={e=>setForm({...form,stage:e.target.value})}><option value="">Choose next stage</option>{['prepress','production','finishing','qc','ready'].map(s=><option key={s}>{s}</option>)}</select></label>{field('notes','Production notes','text',false)}{button}</form></article></>}
 {(mode==='artwork'||mode==='operations')&&<article className={card}><h2 className="font-bold">Issue an artwork proof</h2><form className={grid} onSubmit={e=>void submit(e,'print_issue_artwork_proof',{p_artwork:form.artwork})}>{select('artwork','Artwork',data.print_artworks||[],r=>String(r.title)+' — version '+String(r.version))}{button}</form></article>}
 {(mode==='inventory'||mode==='operations')&&<article className={card}><h2 className="font-bold">Record stock movement</h2><form className={grid} onSubmit={e=>void submit(e,'print_adjust_stock',{p_inventory:form.inventory,p_movement:form.movement,p_quantity:Number(form.quantity),p_notes:form.stock_notes,p_job:form.job||null})}>{select('inventory','Stock item',data.print_inventory||[],r=>String(r.item_name)+' — '+String(r.quantity)+' '+String(r.unit))}<label>Movement<select required className={input} value={form.movement||''} onChange={e=>setForm({...form,movement:e.target.value})}><option value="">Choose movement</option><option value="receipt">Received stock</option><option value="use">Used stock</option><option value="adjustment">Correction (+ or −)</option></select></label>{field('quantity','Quantity','number')}{field('stock_notes','Reason / supplier reference')}{button}</form></article>}
 {(mode==='qc'||mode==='operations')&&<article className={card}><h2 className="font-bold">Record quality control</h2><form className={grid} onSubmit={e=>void submit(e,'print_record_qc',{p_job:form.job,p_passed:form.qc==='passed',p_notes:form.qc_notes||null})}>{select('job','Production job',(data.print_jobs||[]).filter(r=>r.stage==='qc'),r=>String(r.id).slice(0,8)+' — '+String(r.stage))}<label>QC result<select required className={input} value={form.qc||''} onChange={e=>setForm({...form,qc:e.target.value})}><option value="">Choose result</option><option value="passed">Passed</option><option value="failed">Failed — rework required</option></select></label>{field('qc_notes','Inspection / defect notes','text',form.qc==='failed')}{button}</form></article>}
 {(mode==='delivery'||mode==='operations')&&<article className={card}><h2 className="font-bold">Dispatch or confirm collection</h2><form className={grid} onSubmit={e=>void submit(e,'print_dispatch_order',{p_order:form.order,p_status:form.delivery_status,p_recipient:form.recipient,p_tracking:form.tracking||null})}>{orderSelect}<label>Fulfilment update<select required className={input} value={form.delivery_status||''} onChange={e=>setForm({...form,delivery_status:e.target.value})}><option value="">Choose update</option><option value="dispatched">Dispatched</option><option value="delivered">Delivered</option><option value="collected">Collected</option></select></label>{field('recipient','Recipient / collector')}{field('tracking','Courier tracking reference','text',false)}{button}</form></article>}
 </section>;
}
